### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by pkruithof** [jmikola/AutoLogin#16]
The versions for PHP and the Symfony components are quite outdated. They are also not supported anymore. With the arrival of Symfony 3 this library (and it's bundle) can not be installed anymore.

I'm willing to work on a PR for this, in which I also up the version requirements to PHP 5.5.9 (in line with Symfony, and PHP 5.5 will be EOL in 6 months), and Symfony 2.7 and up. Symfony 2.3 is still maintained for a couple of months, but I think a next major release can set stricter requirements. Older Symfony projects can just use an older version imo.

I wanted your thoughts before starting to work on this though.

**Comment by pkruithof** [comment]
Ping @jmikola

**Comment by jmikola** [comment]
> I'm willing to work on a PR for this, in which I also up the version requirements to PHP 5.5.9 (in line with Symfony, and PHP 5.5 will be EOL in 6 months), and Symfony 2.7 and up.

Unless we need to introduce new PHP syntax (e.g. traits), I see no reason to bump the PHP requirement in `composer.json`. Composer will end up enforcing the stricter requirement of Symfony anyway.

I just looked into upgrading the library and bundle by installing it within a new Symfony 3.0 project, and I believe the only relevant change to account for is `Symfony\Component\HttpKernel\Log\LoggerInterface` changing to `Psr\Log\LoggerInterface` (documented [here](https://github.com/symfony/symfony/blob/cef7e5b1b08f9df70bf059dd41070ebfb35e664d/UPGRADE-3.0.md#httpkernel)). This requires changing the LoggerInterface type hint in `Jmikola\AutoLogin\Http\Firewall\AutoLoginListener`. Doing so would be a BC break and theoretically require a bump to 2.0; however, I relaxing the type hint and structuring the code to work with either logger would allow AutoLogin to work with 2.x and 3.0 alike.

I perused the DependencyInjection and Security sections of the 3.0 upgrade notes and I don't believe any of the other changes are relevant to the library/bundle. Would you like to confirm that?

**Comment by jmikola** [comment]
@pkruithof: Please take a look at the referenced PRs and let me know if that works for you.

**Comment by pkruithof** [comment]
Hi, we've since implemented our own autologin feature, basing your work on the new AbstractGuardAuthenticator class in Symfony. This enabled us to get the feature in 2 simple classes, and removing a dependency. So I cannot test the PR's in our project anymore.

**Comment by jmikola** [comment]
https://github.com/jmikola/AutoLogin/pull/18 has been merged, so this can be closed.

**Comment by jmikola** [comment]
Released: 

 * https://github.com/jmikola/AutoLogin/releases/tag/1.2.3
 * https://github.com/jmikola/JmikolaAutoLoginBundle/releases/tag/v1.1.2
