### ISSUE TITLE
Fallback?

### ISSUE THREAD

**Issue by amcastror** [jmikola/AutoLogin#17]
Hi,

I understand that I can configure this on any existing firewall. My question then is: if the request doesn't have the parameter or the parameter is somehow invalid, will it fallback to form login logic?

Thanks a lot!

**Comment by jmikola** [comment]
If the token is not found in the request [`Jmikola\AutoLogin\Http\Firewall\AutoLoginListener::handle()`](https://github.com/jmikola/AutoLogin/blob/212cce9f04ddec5e67196f440c83daf0923adf4c/src/Jmikola/AutoLogin/Http/Firewall/AutoLoginListener.php#L67) should return early and control should proceed to the next listener in the chain.
